### ISSUE TITLE
fix: update `@wesleytodd/buildcss` to 0.0.6

### ISSUE THREAD

**Issue by SgtPooki** [pkgjs/statusboard#16]
https://github.com/pkgjs/statusboard/blob/340401633fc3bde1eaa039d6006ed36a8810bd09/package.json#L42

Need to upgrade this to get the fix from https://github.com/wesleytodd/buildcss/commit/c4b16ce88de5e633cb324f00d45c53c1e8958f75

Otherwise, you get the following error: 

```bash
node:internal/fs/utils:905
  throw new ERR_INVALID_ARG_TYPE(
  ^

TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of SourceMapGenerator
    at Object.writeFile (node:fs:2271:5)
    at /Users/sgtpooki/code/work/foss/pkgjs/statusboard/node_modules/@wesleytodd/buildcss/index.js:105:20
    at /Users/sgtpooki/code/work/foss/pkgjs/statusboard/node_modules/graceful-fs/graceful-fs.js:61:14
    at FSReqCallback.oncomplete (node:fs:200:23) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

**Comment by SgtPooki** [comment]
tested locally with `npm run site`. simply updating the dependency fixes the error.

**Comment by wesleytodd** [comment]
Thanks! I really wish some actual UI person would come along and just replace the UI part of this with something better. But in the mean time my really old build scripts should still be fine.

**Comment by SgtPooki** [comment]
@wesleytodd i've been toying with improvements at https://github.com/SgtPooki/statusboard but haven't gotten into the template engine or UI at all yet. Only get a chance to do it on my freetime
